version: '3.2'

services:
    laravel:
        image: website
        restart: always
        build:
            context: ./
            dockerfile: ./app.docker
        networks:
            - laravel-network
        links:
            - memcached:memcached
            - redis:redis
        ports:
            - "8888:80"
        volumes:
            - ./laravel-config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./laravel-app:/var/www/html
        environment:
            ENVIRONMENT: development
    memcached:
        image: memcached
        ports:
            - "11288:11211"
    redis:
        image: redis
        command: redis-server --requirepass johnpaul
        ports:
            - "6388:6379"
networks:
    laravel-network:
        driver: bridge
